"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from target_lock.protos.lockon import gym_env_pb2 as _gym_env_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ArmEnvStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ArmEnvAsyncStub: ...
    StreamEnv: _grpc.StreamStreamMultiCallable[_gym_env_pb2.EnvRequest, _gym_env_pb2.EnvReply]
    """单一的双向流，客户端发命令，服务端回结果。"""

@_typing.type_check_only
class ArmEnvAsyncStub(ArmEnvStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    StreamEnv: _aio.StreamStreamMultiCallable[_gym_env_pb2.EnvRequest, _gym_env_pb2.EnvReply]  # type: ignore[assignment]
    """单一的双向流，客户端发命令，服务端回结果。"""

class ArmEnvServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def StreamEnv(
        self,
        request_iterator: _MaybeAsyncIterator[_gym_env_pb2.EnvRequest],
        context: _ServicerContext,
    ) -> _typing.Union[_abc.Iterator[_gym_env_pb2.EnvReply], _abc.AsyncIterator[_gym_env_pb2.EnvReply]]:
        """单一的双向流，客户端发命令，服务端回结果。"""

def add_ArmEnvServicer_to_server(servicer: ArmEnvServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
