"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import struct_pb2 as _struct_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Tensor(_message.Message):
    """===== 通用张量结构 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    """numpy.tobytes() 序列化后的原始字节"""
    dtype: _builtins.str
    """数据类型，如 "float32", "uint8", "int64" """
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """张量维度，例如 [84, 84, 3]"""

    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        dtype: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "dtype", b"dtype", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Tensor: _TypeAlias = Tensor  # noqa: Y015

@_typing.final
class EnvRequest(_message.Message):
    """===== 客户端请求 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    RESET_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reset(self) -> Global___Reset: ...
    @_builtins.property
    def step(self) -> Global___Step: ...
    @_builtins.property
    def close(self) -> Global___Close: ...
    def __init__(
        self,
        *,
        reset: Global___Reset | None = ...,
        step: Global___Step | None = ...,
        close: Global___Close | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "cmd", b"cmd", "reset", b"reset", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "cmd", b"cmd", "reset", b"reset", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_cmd: _TypeAlias = _typing.Literal["reset", "step", "close"]  # noqa: Y015
    _WhichOneofArgType_cmd: _TypeAlias = _typing.Literal["cmd", b"cmd"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_cmd) -> _WhichOneofReturnType_cmd | None: ...

Global___EnvRequest: _TypeAlias = EnvRequest  # noqa: Y015

@_typing.final
class EnvReply(_message.Message):
    """===== 服务端回复 ====="""

    DESCRIPTOR: _descriptor.Descriptor

    RESET_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def reset(self) -> Global___ResetReply: ...
    @_builtins.property
    def step(self) -> Global___StepReply: ...
    @_builtins.property
    def close(self) -> Global___CloseReply: ...
    def __init__(
        self,
        *,
        reset: Global___ResetReply | None = ...,
        step: Global___StepReply | None = ...,
        close: Global___CloseReply | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "reset", b"reset", "result", b"result", "step", b"step"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "reset", b"reset", "result", b"result", "step", b"step"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_result: _TypeAlias = _typing.Literal["reset", "step", "close"]  # noqa: Y015
    _WhichOneofArgType_result: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_result) -> _WhichOneofReturnType_result | None: ...

Global___EnvReply: _TypeAlias = EnvReply  # noqa: Y015

@_typing.final
class Reset(_message.Message):
    """===== Reset ====="""

    DESCRIPTOR: _descriptor.Descriptor

    SEED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def seed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        seed: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Reset: _TypeAlias = Reset  # noqa: Y015

@_typing.final
class ResetReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBSERVATION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def observation(self) -> Global___Tensor: ...
    def __init__(
        self,
        *,
        observation: Global___Tensor | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["observation", b"observation"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["observation", b"observation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ResetReply: _TypeAlias = ResetReply  # noqa: Y015

@_typing.final
class Step(_message.Message):
    """===== Step ====="""

    DESCRIPTOR: _descriptor.Descriptor

    ACTION_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def action(self) -> Global___Tensor: ...
    def __init__(
        self,
        *,
        action: Global___Tensor | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Step: _TypeAlias = Step  # noqa: Y015

@_typing.final
class StepReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OBSERVATION_FIELD_NUMBER: _builtins.int
    REWARD_FIELD_NUMBER: _builtins.int
    TERMINATED_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def observation(self) -> Global___Tensor: ...
    @_builtins.property
    def reward(self) -> Global___Tensor: ...
    @_builtins.property
    def terminated(self) -> Global___Tensor: ...
    @_builtins.property
    def truncated(self) -> Global___Tensor: ...
    @_builtins.property
    def info(self) -> _struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        observation: Global___Tensor | None = ...,
        reward: Global___Tensor | None = ...,
        terminated: Global___Tensor | None = ...,
        truncated: Global___Tensor | None = ...,
        info: _struct_pb2.Struct | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation", "reward", b"reward", "terminated", b"terminated", "truncated", b"truncated"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["info", b"info", "observation", b"observation", "reward", b"reward", "terminated", b"terminated", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___StepReply: _TypeAlias = StepReply  # noqa: Y015

@_typing.final
class Close(_message.Message):
    """===== Close ====="""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Close: _TypeAlias = Close  # noqa: Y015

@_typing.final
class CloseReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___CloseReply: _TypeAlias = CloseReply  # noqa: Y015
